package com.example.satelliteai.common.exception;

public enum ErrorCode {
	INVALID_FILE,
	UNSUPPORTED_FORMAT,
	MISSING_CRS,
	INVALID_BAND_MAPPING,
	NO_OVERLAP,
	INCOMPATIBLE_RASTERS,
	REPROJECTION_FAILED,
	RESAMPLING_FAILED,
	ALIGNMENT_FAILED,
	PREPROCESSING_FAILED,
	VLM_NOT_AVAILABLE,
	VLM_LOAD_FAILED,
	VLM_INFERENCE_FAILED,
	PYTHON_SERVICE_UNAVAILABLE,
	STORAGE_ERROR,
	JOB_FAILED,
	PROJECT_NOT_FOUND,
	ASSET_NOT_FOUND,
	PAIR_NOT_FOUND,
	INVALID_PAIR,
	VALIDATION_FAILED,
	INTERNAL_ERROR
}
